### ISSUE TITLE
Tracking issue: Context queries

### ISSUE THREAD

**Issue by novusnota** [novusnota-forks/helix-sticky-context#1]
Intersection of list of languages in Helix and in nvim-treesitter-context:

- [ ] bash:       `context.scm`
- [x] c:          `context.scm`
- [ ] capnp:      `context.scm`
- [ ] clojure:    `context.scm`
- [ ] cmake:      `context.scm`
- [x] cpp:        `context.scm`
- [ ] css:        `context.scm`
- [ ] cue:        `context.scm`
- [ ] d:          `context.scm`
- [ ] dart:       `context.scm`
- [ ] diff:       `context.scm`
- [x] elixir:     `context.scm`
- [ ] fish:       `context.scm`
- [ ] fortran:    `context.scm`
- [ ] gdscript:   `context.scm`
- [x] go:         `context.scm`
- [ ] graphql:    `context.scm`
- [ ] groovy:     `context.scm`
- [ ] haskell:    `context.scm`
- [x] html:       `context.scm`
- [ ] ini:        `context.scm`
- [ ] java:       `context.scm`
- [x] javascript: `context.scm`
- [x] json:       `context.scm`
- [ ] jsonnet:    `context.scm`
- [ ] julia:      `context.scm`
- [ ] latex:      `context.scm`
- [ ] lua:        `context.scm`
- [ ] make:       `context.scm`
- [x] markdown:   `context.scm`
- [x] matlab:     `context.scm`
- [ ] nim:        `context.scm`
- [x] nix:        `context.scm`
- [ ] ocaml:      `context.scm`
- [ ] odin:       `context.scm`
- [ ] org:        `context.scm`
- [ ] php:        `context.scm`
- [ ] prisma:     `context.scm`
- [x] python:     `context.scm`
- [ ] r:          `context.scm`
- [ ] ruby:       `context.scm`
- [x] rust:       `context.scm`
- [x] scala:      `context.scm`
- [ ] scss:       `context.scm`
- [ ] smali:      `context.scm`
- [ ] solidity:   `context.scm`
- [ ] svelte:     `context.scm`
- [ ] swift:      `context.scm`
- [ ] templ:      `context.scm`
- [x] toml:       `context.scm`
- [x] tsx:        `context.scm`
- [x] typescript: `context.scm`
- [ ] verilog:    `context.scm`
- [ ] vue:        `context.scm`
- [ ] xml:        `context.scm`
- [x] yaml:       `context.scm`

Plus a couple of languages, which I've recently added to Helix, but not to Neovim yet:
- [ ] tact:        `context.scm`
- [ ] ohm:       `context.scm`

Exist in `helix/sticky-context`, but not in Neovim/Helix (?):
- jsx
- ecma
- zig
